import { GoogleGenAI } from "@google/genai";

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    try {
        const { prompt } = req.body;
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        
        const artisticPrompt = `A dreamlike, ethereal, and surreal digital painting of: ${prompt}. Use a soft, glowing color palette.`;

        // OPTIMIZATION: Switched to gemini-2.5-flash-image (Nano/Banana) for faster generation.
        // We use generateContent instead of generateImages for this model family.
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [{ text: artisticPrompt }]
            },
            // Note: responseMimeType and responseSchema are NOT supported for this model.
        });
        
        let imageUrl = null;
        
        // Iterate through parts to find the inline image data
        if (response.candidates?.[0]?.content?.parts) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                    break;
                }
            }
        }

        if (!imageUrl) {
            throw new Error("No image generated by the model.");
        }

        res.status(200).json({ imageUrl });

    } catch (error) {
        console.error("Error in generateDreamImage API:", error);
        res.status(500).json({ error: "Failed to generate dream image." });
    }
}